export const LOAD_COUNTS = 'app/Home/LOAD_COUNTS';
export const COUNTS_LOADING_SUCCESS = 'app/Home/COUNTS_LOADING_SUCCESS';
export const COUNTS_LOADING_ERROR = 'app/Home/COUNTS_LOADING_ERROR';
export const FETCH_HOMEPAGE = 'app/Home/FETCH_HOMEPAGE';
export const FETCH_HOMEPAGE_ERROR = 'app/Home/FETCH_HOMEPAGE_ERROR';
export const FETCH_HOMEPAGE_SUCCESS = 'app/Home/FETCH_HOMEPAGE_SUCCESS';
